name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.12.1

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: ${{ secrets.VPS_PORT }}
        source: ".next,public,package.json,pnpm-lock.yaml"
        target: "/var/www/website/trae"
        rm: true

    - name: Restart application
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /var/www/website/trae
          pnpm install --production
          pm2 restart trae-ai || PORT=3007 pm2 start npm --name "trae-ai" -- start
          pm2 save